### ISSUE TITLE
notBefore and notAfter in personography.xml

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#127]
Does personography.xml handle notBefore and notAfter tags?

Please consider the following example:
`               <person xml:id="KING12">
                  <persName when="1878">
                     <surname>King</surname>,
                     <forename>George</forename>
                     <forename>Gerald</forename>
                  </persName>
                  <affiliation when="1878" n="AB/SK House of Commons" ref="plc:QUEE2">Queen's</affiliation>
                  <affiliation when="1891" n="AB/SK House of Commons" ref="plc:QUEE2">Queen's</affiliation>
                  <affiliation when="1896" n="AB/SK House of Commons" ref="plc:SUNB2">Sunbury--Queen's</affiliation>
                  <affiliation when="1896" n="AB/SK House of Commons" ref="plc:QUEE2">Queen's</affiliation>
               </person>`

In order to know which riding to assign this historical figure's 1896 comments to, I assume I need to define the dates of his tenure as an MP for each riding? If this can be done, may I ask what the syntax for this would be?

**Comment by martindholmes** [comment]
We don't have any mechanism for assigning anyone's comment to a subset of themselves; they're just attached to the person. Of course the comments themselves have a date, so a reader can probably figure out what role the person was filling at that time. 

We could devise an elaborate mechanism using dating attributes and a lot of cunning XSLT, but to be brutally honest there will never be time for me to implement it. No new features is the watchword, otherwise we'll never finish the project at all.

**Comment by DanielHeidt** [comment]
Agreed. Not looking for new features. I found a workaround in the meantime.
