### ISSUE TITLE
OCR Erasmus content

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#16]
I uploaded the Erasmus content, it just needs to be processed before posting. The images have a bit of bleed-through from text on the other side of the page, so it might be worth doing a batch tweak on the brightness / contrast. I can perform this first, if you think that it is a good idea.

Dan

**Comment by martindholmes** [comment]
I was just starting to run OCR on these, but I notice the folder structure is all screwed up. There was a folder with a space in its name (data/Indigenous Voices), which I've renamed to data/Indigenous_Voices, but now I see there's a duplicate "Indigenous Voices" folder inside that. Could you clean up the folders before I start? I don't want to start deleting duplicates because I don't know which versions you need.

**Comment by DanielHeidt** [comment]
I cleaned up a few folders (including the one you mention). One of the folders, however, didn't have any files in it (just an empty directory). I'm not sure if my deletion was tracked. If this empty folder still exists, please delete it on your end (I think my GUI doesn't catch changes unless there are files in it).

**Comment by martindholmes** [comment]
Great, OCRing now. If the results are horrible, you could clean up some images and we'll try again to see if it improves anything.

**Comment by martindholmes** [comment]
OCR results now pushed to the repo. Check them out and see whether you think it's worth cleaning up the images.

**Comment by DanielHeidt** [comment]
The results look excellent to me. I'll upload them to the transcription platform later tonight. Thanks again.

**Comment by martindholmes** [comment]
Seems to be done. Closing the ticket.
