### ISSUE TITLE
French Name Mark-Up

### ISSUE THREAD

**Issue by lyallg** [TheCanadianConfederationDebates/TCCD#55]
I have started developing some of the French Que-Ont TEI. By May I think we should have a bilingual person to mark-up these names.

**Comment by martindholmes** [comment]
The names aren't different, though, surely? Do we really need someone bilingual, or just someone who can parse the French in a basic way to identify speaker names?

**Comment by lyallg** [comment]
My concern is that an English speaker with NO knowledge of French will not be able to distinguish speakers from people being quoted. Maybe I am wrong?

**Comment by lyallg** [comment]
Maybe I am wrong the first doc I did seemed ambiguous but the second one has more speakers and appears more obvious. Maybe we can return to this in a few weeks,

**Comment by DanielHeidt** [comment]
I am ok with an English speaker identifying the speakers. The formatting is very predictable, and we're not encoding anything else. You can proceed with this work - but talk to me before assigning it. I want to make sure that the encoder has limited (i.e. grade 9) French so that they can pick out things like votes. That is all the French skills that are required.

**Comment by martindholmes** [comment]
@lyallg I wasn't suggesting someone with no knowledge of French; I just think they don't have to be bilingual. I could do it with no trouble, and nobody would accuse me of being bilingual. :-)

**Comment by DanielHeidt** [comment]
Agreed. I think we're on the same page. I will enquire with our encoders and identify who has adequate French competencies.

**Comment by lyallg** [comment]
Sounds good.
