### ISSUE TITLE
Add links to bibliographical references in debate day HTML

### ISSUE THREAD

**Issue by martindholmes** [TheCanadianConfederationDebates/TCCD#75]
Each debate day should have, at the end of the text and before the participant list, a rendering of the bibliography item from bibliography.xml representing its source; where this include a ref tag, make it a link to the target.

**Comment by DanielHeidt** [comment]
Dan to standardize bibliography XML IDs to match debate day IDs - ex. lgNS_LA becomes lgNSLA

**Comment by DanielHeidt** [comment]
Add from to fields to H of C records as per lgNS_LA. Can be months 1872-mm-dd.

**Comment by martindholmes** [comment]
Citation should go at the end of the debate day content, before the lists of people etc.

**Comment by DanielHeidt** [comment]
Note to Dan - Sequence of bibl has to match chicago style

**Comment by DanielHeidt** [comment]
I spent most of the morning adding content to bibliography.xml. Gord then gave me some feedback. Oxygen says the tags all check out though there are likely a few incongruities that I missed, or meta data that might be entered in a slightly different way than it currently appears. 

@martindholmes please have a look when you have a chance and see if you can use what is there to build the citations described in this ticket. If you need further changes made to bibliography.xml, just let me know.

**Comment by martindholmes** [comment]
Hi Dan,

It's valid. I did see this:

<date when="1874">2014</date>

which is a bit odd -- which date is intended?

I'll try to get a start on this before the end of the week.

Cheers,
Martin

**Comment by DanielHeidt** [comment]
Thanks for keeping on this.

Yes, there are several entries like the one you mentioned and I was planning on bringing it to your attention at the next meeting. I need a bit more information about the meta data to resolve this issue. My question is what the fields communicate. If <date when> indicates the date the information was communicated, then it should be 1874. If it is the date of publication then it should be 2014 because that is when the volume was compiled for newspaper records. Once I know what the fields indicate, I'll update the content.

**Comment by martindholmes** [comment]
They're not fields, they're tags; in this case, the position of the date in the citation should communicate what it indicates, based on the style guide you're using. The basic approach is to create a citation exactly as you would for any publication, and then just tag the components of it that it's helpful to tag.

**Comment by DanielHeidt** [comment]
Question for @martindholmes.

Please have a quick look at the example below:
`        <bibl xml:id="lgHC_1873_1" n="H of C – Fed. 1873 1st Session"><publisher>Canada</publisher>. <title level="m">House of Commons Debates, 1873 First Session</title>. Edited by <editor>David Farr</editor>. <pubPlace>Ottawa</pubPlace>: <publisher>Library of Parliament</publisher>. Original scans accessible at: <date from="1873-03-05" to="1873-08-13">2013</date>. <ref target="http://parl.canadiana.ca/">http://parl.canadiana.ca/</ref>.</bibl>`

In this case, I believe you expressed a desire in having access to exact start-end dates so that you can produce the right citation at the end of a debate day. In this case, however, the publication date (2013) does not match the content dates (from 1873).

Could the unique IDs for these pre-1875 House of Commons volumes instead be inserted into the debate days? If yes, this ID, instead of <date from> and <date to> could be used to determine which citation to use. That would allow me to simply enter the publication date. 

Let me know what you think is best.

**Comment by martindholmes** [comment]
I don't really understand "Original scans accessible at: 2013." What could that possibly mean?

We can't really mix up the two dates in a single element like this. If there's no place in the citation itself to specify the date range covered, then you could provide an empty date element with `@from` and `@to` to specify the range:

<date from="1873-03-05" to="1873-08-13"/>

It doesn't really matter where this goes, since it has no content. The 2013 date should be:

<date when="2013">2013</date>

**Comment by martindholmes** [comment]
I think my part of this is done now. I've uploaded the results; check that you're seeing what you expect to see, or if no source is found, that it's clear why.

**Comment by DanielHeidt** [comment]
I agree that this feature appears to be working well. Thanks for turning it around quickly and for catching the data entry errors — I put a couple of tags in the wrong order. Most are now fixed, but I will give the site a thorough checking before asking you to perform another rebuild sometime tomorrow.

**Comment by martindholmes** [comment]
When you're happy, close the ticket. I'll move on to the other priority one in the meantime.

**Comment by DanielHeidt** [comment]
Just about everything is working. 

The only bug I've found is the H of C debates for the pre-1875 period. http://hcmc.uvic.ca/confederation/en/lgHC_NFLD_1868-04-06.html, for example, appears to be displaying the citation for ID "lgHC" instead of "lgHC_1867-1868".

I see the same problem in http://hcmc.uvic.ca/confederation/en/lgHC_NFLD_1870-02-17.html. If I am not correctly assigning IDs in the bibliography, let me know and I'll fix them.

**Comment by martindholmes** [comment]
I think that's because this:

~~~~~
<bibl xml:id="lgHC_1867-1868" n="H of C – Fed. 1867-1868"><publisher>Canada</publisher>. <title level="m">House of Commons Debates, 1867-1868</title>. Edited by <editor>P.B. Waite</editor>. <pubPlace>Ottawa</pubPlace>: <publisher>Queen's Printer</publisher>, <date when="1967">1967</date>. Original scans accessible at: <ref target="http://parl.canadiana.ca/">http://parl.canadiana.ca/</ref>.
        </bibl>
~~~~~

doesn't have a date with `@from` and `@to`.

**Comment by martindholmes** [comment]
All volumes which deal only with a partial date range need to have the date element with those attributes. It makes no sense to try to parse both the id and the date element to find the applicable range; there should be just one mechanism for encoding each feature.

**Comment by DanielHeidt** [comment]
I can add the `@from` and `@to`, but assumed that this would conflict with the `<date>` tag that is already in each field. Was I incorrect?

**Comment by martindholmes** [comment]
We settled on adding an empty date tag to cover the range, didn't we?

**Comment by DanielHeidt** [comment]
Will. I think Gord and I got our wires crossed. I've updated bibliography.xml. Does the H of C section (lines 75 to 95) now provide the necessary metadata in the correct tags?

**Comment by DanielHeidt** [comment]
So after some digging, I had a chat with Gord, and he suggested a really simple solution: harvest the <bibl> info at the beginning of each debate day to produce a citation.

The only tricky part is that the <bibl> content does not contain URLs to the source scans / archives. The simplest way to add this content to the citations listed at the bottom of the debate days on the website is for me to add the URLs to each debate day. I assume the urls would use the <ref target> tag? If yes, I plan to place directly after the <title> tag. So, for example,

`
<bibl>
               <title>Parliamentary Debates on the Subject of the Confederation of the British North American Provinces, 3rd Session, 8th Provincial Parliament of Canada</title>.
          <date when="1865"/>.  
         <pubPlace>Quebec</pubPlace>: <publisher>Hunter, Rose &amp; Co., Parliamentary           <biblScope unit="page" from="25" to="45"/>.
        </bibl>
`

would become:
`
<bibl>
               <title>Parliamentary Debates on the Subject of the Confederation of the British North American Provinces, 3rd Session, 8th Provincial Parliament of Canada</title>.<ref target="https://goo.gl/kdW3S2">
          <date when="1865"/>.  
         <pubPlace>Quebec</pubPlace>: <publisher>Hunter, Rose &amp; Co., Parliamentary           <biblScope unit="page" from="25" to="45"/>.
        </bibl>
`
The ajax can then grab these <bibl> tags, italicize the <title> tag while also turning it into a hyperlink using the URL contained in <ref>.

Does that sound good?

If we proceed with this solution, would bibliography.xml still have a purpose?

**Comment by martindholmes** [comment]
MDH to make the change to the schema to constrain the sourceDesc/bibl/@corresp values to bibl:ids from the bibliography. Then update the rendering code so that these pointers are used to create the citation. DH to add the pointers.

**Comment by martindholmes** [comment]
My part of this is done in commit #c9240f428. I've also added the correct value to the BC 1871 Federal docs for testing purposes. Since this replaces the previous process, I won't upload a rebuild of the site until all the `<bibl>/@corresp` values are added.

**Comment by DanielHeidt** [comment]
All done and appears to be running well.
