### ISSUE TITLE
anonymous image implementation

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#90]
For all speakers who do not have a photo, please have the popup profile display /Users/danielhheidt/TCCD/code/html/images/generic.jpg.

**Comment by martindholmes** [comment]
The portrait image is a background graphic based on the id, so that's not so easy. Are there people for whom no portraits exist?

**Comment by DanielHeidt** [comment]
There are only portraits for about 1/4 of the roughly 2,000 historical figures. During the build process, would it be possible to check whether a portrait exists, and if not, display the generic image for that historical figure?

**Comment by martindholmes** [comment]
The issue is caused by the decision to use CSS to display the image as a background graphic; that means it gets generated on the fly, so the build has no control over it. If we could prevail upon Frank to allow us to use an actual image tag, then we could do it more easily.

**Comment by DanielHeidt** [comment]
@FrankFlitton - if Martin implemented the solution for image tags he mentions in the above post, would that be ok with you?

**Comment by martindholmes** [comment]
Fixed this. It's daft to have a blank or generic image taking up a huge amount of space and forcing the user to scroll in a dialog box when they don't need to, so I've set it up so that when there's no available portrait, the space is not wasted. This is also important for the display of popups not related to the personography such as footnotes.
